POST http://localhost:8081/api/code/new
Content-Type: application/json

"code: newCode"

###
GET http://localhost:8081/code
Accept: application/json

###
GET http://localhost:8081/api/code
Accept: application/json

###
GET http://localhost:8081/code/new
Accept: application/json
