GET http://localhost:8082/api/code/1
Accept: application/json

###
POST http://localhost:8082/api/code/new
Content-Type: application/json

{
  "code": "<newcode>"
}

###
GET http://localhost:8082/api/code/latest
Accept: application/json


###
GET http://localhost:8082/code/1
Accept: application/json

###
GET http://localhost:8082/code/new
Accept: application/json

###
GET http://localhost:8082/code/latest
Accept: application/json
